name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests with coverage
      run: |
        pip install coverage
        coverage run -m unittest discover tests
    - name: Generate coverage report
      run: |
        coverage report
        coverage xml
    - name: Generate badge
      run: |
        pip install genbadge
        genbadge coverage -i coverage.xml -o .github/coverage_badge.svg
    - name: Upload coverage badge
      uses: actions/upload-artifact@v2
      with:
        name: coverage_badge
        path: .github/coverage_badge.svg
